### ISSUE TITLE
Patients look like they are being added directly to OPAT Current on 0.6 until you refresh

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#1019]
This is incorrect IIRC. No matter which OPAT list you are on the person should be added to OPAT-Referral List.

**Comment by michaeledwardmarks** [comment]
Ah interesting.
What acutally happens is as follows.
1) On OPAT Current
2) Add Patient
3) Patient Appears on the List
4) Move to OPAT Referral
5) Patient is actually on OPAT Referral List
6) Go back to OPAT Current - Patient (correctly) isn't there

If you refresh at Step 4 rather than move to OPAT referral the patient also (correctly) disappears from OPAT-Current

**Comment by davidmiller** [comment]
This should now be fixed and deployed to elcid-uch-test. 

Note this doesn't include fixing #752
(Which is in fact not as trivial as it seems because reasons.)

**Comment by michaeledwardmarks** [comment]
Still showing up on OPAT Current for me.
Tried refresh and login/logout.

**Comment by michaeledwardmarks** [comment]
Multiple (*4!) hard refreshes later it is indeed fixed.
Weird.
