### ISSUE TITLE
Add Patient for Walk-In and OPAT broken

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#608]
__Walk-In__
Click Add Patient Button (as opposed to the Referral Portal)
Search Hospital Number Modal comes up
Type Hospital Number, click Search.
Northing happens.

In Debugging it shows:
GET http://elcid04.herokuapp.com/templates/modals/add_walkin_episode.html/ 500 (INTERNAL SERVER ERROR)angular.28f401490ec3.js:8495 (anonymous function)angular.28f401490ec3.js:8291 sendReqangular.28f401490ec3.js:8025 serverRequestangular.28f401490ec3.js:11498 wrappedCallbackangular.28f401490ec3.js:11498 wrappedCallbackangular.28f401490ec3.js:11584 (anonymous function)angular.28f401490ec3.js:12608 Scope.$evalangular.28f401490ec3.js:12420 Scope.$digestangular.28f401490ec3.js:12712 Scope.$applyangular.28f401490ec3.js:8315 doneangular.28f401490ec3.js:8527 completeRequestangular.28f401490ec3.js:8466 xhr.onreadystatechange

__Slightly different for OPAT__
Click Add Patient button
The Search Hospital Modal doesn't even come up
Debugging gets:
GET http://elcid04.herokuapp.com/templates/modals/opat_referral.html/ 500 (INTERNAL SERVER ERROR)angular.28f401490ec3.js:8495 (anonymous function)angular.28f401490ec3.js:8291 sendReqangular.28f401490ec3.js:8025 $get.serverRequestangular.28f401490ec3.js:11498 deferred.promise.then.wrappedCallbackangular.28f401490ec3.js:11498 deferred.promise.then.wrappedCallbackangular.28f401490ec3.js:11584 (anonymous function)angular.28f401490ec3.js:12608 $get.Scope.$evalangular.28f401490ec3.js:12420 $get.Scope.$digestangular.28f401490ec3.js:12712 $get.Scope.$applyangular.28f401490ec3.js:18980 (anonymous function)jquery.3b80424646a7.js:4624 jQuery.event.dispatchjquery.3b80424646a7.js:4292 jQuery.event.add.elemData.handle

**Comment by davidmiller** [comment]
@michaeledwardmarks this is fixed now and deployed to http://elcid04-test.herokuapp.com/#/list/walkin/walkin_triage

**Comment by michaeledwardmarks** [comment]
Not sure deployed.
Walk-In I still get:
GET http://elcid04.herokuapp.com/templates/modals/add_walkin_episode.html/ 500 (INTERNAL SERVER ERROR)(anonymous function) @ angular.28f401490ec3.js:8495sendReq @ angular.28f401490ec3.js:8291serverRequest @ angular.28f401490ec3.js:8025wrappedCallback @ angular.28f401490ec3.js:11498wrappedCallback @ angular.28f401490ec3.js:11498(anonymous function) @ angular.28f401490ec3.js:11584Scope.$eval @ angular.28f401490ec3.js:12608Scope.$digest @ angular.28f401490ec3.js:12420Scope.$apply @ angular.28f401490ec3.js:12712done @ angular.28f401490ec3.js:8315completeRequest @ angular.28f401490ec3.js:8527xhr.onreadystatechange @ angular.28f401490ec3.js:8466

**Comment by davidmiller** [comment]
@michaeledwardmarks I think you may have missed the new test server elcid04-test !

**Comment by michaeledwardmarks** [comment]
Fixed on new server.
